name: shopping_dashboard_screen
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_iconly: ^1.0.2
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1
  fancy_shimmer_image: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  flutter_spinkit: ^5.2.1
  dotted_border: ^2.1.0
  image_picker: ^1.0.7

  #firebase
  cloud_firestore: ^4.16.1
  firebase_core: ^2.29.0
  firebase_database: ^10.5.1
  firebase_auth: ^4.19.1
  uuid: ^4.4.0
  firebase_storage: ^11.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true


  assets:
    - images/
    - images/cat/
    - images/offers/
    - images/landing/

